apiVersion: icodeai.icodeai.io/v1
kind: Profile
metadata:
  name: icodeai
spec:
  owner:
    kind: User
    name: icodeaike@gmail.com
  resourceQuotaSpec:
    hard:
      cpu: "0.5"
      memory: 1Gi
      pods: "1"